/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminPosRouteImport } from './routes/admin/pos'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBillsRouteImport } from './routes/admin/bills'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin/settings/index'
import { Route as AdminSettingsTablesRouteImport } from './routes/admin/settings/tables'
import { Route as AdminSettingsSystemRouteImport } from './routes/admin/settings/system'
import { Route as AdminSettingsStaffRouteImport } from './routes/admin/settings/staff'
import { Route as AdminSettingsReceiptsRouteImport } from './routes/admin/settings/receipts'
import { Route as AdminSettingsProductsRouteImport } from './routes/admin/settings/products'
import { Route as AdminSettingsPlatformsRouteImport } from './routes/admin/settings/platforms'
import { Route as AdminSettingsMenuRouteImport } from './routes/admin/settings/menu'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin/settings/general'
import { Route as AdminSettingsFinancialRouteImport } from './routes/admin/settings/financial'
import { Route as AdminSettingsAboutRouteImport } from './routes/admin/settings/about'
import { Route as AdminSettingsMenuIndexRouteImport } from './routes/admin/settings/menu/index'
import { Route as AdminSettingsMenuNewRouteImport } from './routes/admin/settings/menu/new'
import { Route as AdminSettingsMenuProductIdEditRouteImport } from './routes/admin/settings/menu/$productId.edit'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillsRoute = AdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsTablesRoute = AdminSettingsTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsSystemRoute = AdminSettingsSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsStaffRoute = AdminSettingsStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsReceiptsRoute = AdminSettingsReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsProductsRoute = AdminSettingsProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPlatformsRoute = AdminSettingsPlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsMenuRoute = AdminSettingsMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsFinancialRoute = AdminSettingsFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsAboutRoute = AdminSettingsAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsMenuIndexRoute = AdminSettingsMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsMenuRoute,
} as any)
const AdminSettingsMenuNewRoute = AdminSettingsMenuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminSettingsMenuRoute,
} as any)
const AdminSettingsMenuProductIdEditRoute =
  AdminSettingsMenuProductIdEditRouteImport.update({
    id: '/$productId/edit',
    path: '/$productId/edit',
    getParentRoute: () => AdminSettingsMenuRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/financial': typeof AdminSettingsFinancialRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/menu': typeof AdminSettingsMenuRouteWithChildren
  '/admin/settings/platforms': typeof AdminSettingsPlatformsRoute
  '/admin/settings/products': typeof AdminSettingsProductsRoute
  '/admin/settings/receipts': typeof AdminSettingsReceiptsRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/settings/tables': typeof AdminSettingsTablesRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/settings/menu/new': typeof AdminSettingsMenuNewRoute
  '/admin/settings/menu/': typeof AdminSettingsMenuIndexRoute
  '/admin/settings/menu/$productId/edit': typeof AdminSettingsMenuProductIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/financial': typeof AdminSettingsFinancialRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/platforms': typeof AdminSettingsPlatformsRoute
  '/admin/settings/products': typeof AdminSettingsProductsRoute
  '/admin/settings/receipts': typeof AdminSettingsReceiptsRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/settings/tables': typeof AdminSettingsTablesRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/admin/settings/menu/new': typeof AdminSettingsMenuNewRoute
  '/admin/settings/menu': typeof AdminSettingsMenuIndexRoute
  '/admin/settings/menu/$productId/edit': typeof AdminSettingsMenuProductIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/kitchen': typeof KitchenRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/settings/about': typeof AdminSettingsAboutRoute
  '/admin/settings/financial': typeof AdminSettingsFinancialRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/menu': typeof AdminSettingsMenuRouteWithChildren
  '/admin/settings/platforms': typeof AdminSettingsPlatformsRoute
  '/admin/settings/products': typeof AdminSettingsProductsRoute
  '/admin/settings/receipts': typeof AdminSettingsReceiptsRoute
  '/admin/settings/staff': typeof AdminSettingsStaffRoute
  '/admin/settings/system': typeof AdminSettingsSystemRoute
  '/admin/settings/tables': typeof AdminSettingsTablesRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/admin/settings/menu/new': typeof AdminSettingsMenuNewRoute
  '/admin/settings/menu/': typeof AdminSettingsMenuIndexRoute
  '/admin/settings/menu/$productId/edit': typeof AdminSettingsMenuProductIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/setup'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/pos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/'
    | '/admin/settings/about'
    | '/admin/settings/financial'
    | '/admin/settings/general'
    | '/admin/settings/menu'
    | '/admin/settings/platforms'
    | '/admin/settings/products'
    | '/admin/settings/receipts'
    | '/admin/settings/staff'
    | '/admin/settings/system'
    | '/admin/settings/tables'
    | '/admin/settings/'
    | '/admin/settings/menu/new'
    | '/admin/settings/menu/'
    | '/admin/settings/menu/$productId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/kitchen'
    | '/login'
    | '/setup'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/pos'
    | '/admin/reports'
    | '/admin'
    | '/admin/settings/about'
    | '/admin/settings/financial'
    | '/admin/settings/general'
    | '/admin/settings/platforms'
    | '/admin/settings/products'
    | '/admin/settings/receipts'
    | '/admin/settings/staff'
    | '/admin/settings/system'
    | '/admin/settings/tables'
    | '/admin/settings'
    | '/admin/settings/menu/new'
    | '/admin/settings/menu'
    | '/admin/settings/menu/$productId/edit'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/kitchen'
    | '/login'
    | '/setup'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/pos'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/'
    | '/admin/settings/about'
    | '/admin/settings/financial'
    | '/admin/settings/general'
    | '/admin/settings/menu'
    | '/admin/settings/platforms'
    | '/admin/settings/products'
    | '/admin/settings/receipts'
    | '/admin/settings/staff'
    | '/admin/settings/system'
    | '/admin/settings/tables'
    | '/admin/settings/'
    | '/admin/settings/menu/new'
    | '/admin/settings/menu/'
    | '/admin/settings/menu/$productId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  KitchenRoute: typeof KitchenRoute
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bills': {
      id: '/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AdminBillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/tables': {
      id: '/admin/settings/tables'
      path: '/tables'
      fullPath: '/admin/settings/tables'
      preLoaderRoute: typeof AdminSettingsTablesRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/system': {
      id: '/admin/settings/system'
      path: '/system'
      fullPath: '/admin/settings/system'
      preLoaderRoute: typeof AdminSettingsSystemRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/staff': {
      id: '/admin/settings/staff'
      path: '/staff'
      fullPath: '/admin/settings/staff'
      preLoaderRoute: typeof AdminSettingsStaffRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/receipts': {
      id: '/admin/settings/receipts'
      path: '/receipts'
      fullPath: '/admin/settings/receipts'
      preLoaderRoute: typeof AdminSettingsReceiptsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/products': {
      id: '/admin/settings/products'
      path: '/products'
      fullPath: '/admin/settings/products'
      preLoaderRoute: typeof AdminSettingsProductsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/platforms': {
      id: '/admin/settings/platforms'
      path: '/platforms'
      fullPath: '/admin/settings/platforms'
      preLoaderRoute: typeof AdminSettingsPlatformsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/menu': {
      id: '/admin/settings/menu'
      path: '/menu'
      fullPath: '/admin/settings/menu'
      preLoaderRoute: typeof AdminSettingsMenuRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/financial': {
      id: '/admin/settings/financial'
      path: '/financial'
      fullPath: '/admin/settings/financial'
      preLoaderRoute: typeof AdminSettingsFinancialRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/about': {
      id: '/admin/settings/about'
      path: '/about'
      fullPath: '/admin/settings/about'
      preLoaderRoute: typeof AdminSettingsAboutRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/menu/': {
      id: '/admin/settings/menu/'
      path: '/'
      fullPath: '/admin/settings/menu/'
      preLoaderRoute: typeof AdminSettingsMenuIndexRouteImport
      parentRoute: typeof AdminSettingsMenuRoute
    }
    '/admin/settings/menu/new': {
      id: '/admin/settings/menu/new'
      path: '/new'
      fullPath: '/admin/settings/menu/new'
      preLoaderRoute: typeof AdminSettingsMenuNewRouteImport
      parentRoute: typeof AdminSettingsMenuRoute
    }
    '/admin/settings/menu/$productId/edit': {
      id: '/admin/settings/menu/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/admin/settings/menu/$productId/edit'
      preLoaderRoute: typeof AdminSettingsMenuProductIdEditRouteImport
      parentRoute: typeof AdminSettingsMenuRoute
    }
  }
}

interface AdminSettingsMenuRouteChildren {
  AdminSettingsMenuNewRoute: typeof AdminSettingsMenuNewRoute
  AdminSettingsMenuIndexRoute: typeof AdminSettingsMenuIndexRoute
  AdminSettingsMenuProductIdEditRoute: typeof AdminSettingsMenuProductIdEditRoute
}

const AdminSettingsMenuRouteChildren: AdminSettingsMenuRouteChildren = {
  AdminSettingsMenuNewRoute: AdminSettingsMenuNewRoute,
  AdminSettingsMenuIndexRoute: AdminSettingsMenuIndexRoute,
  AdminSettingsMenuProductIdEditRoute: AdminSettingsMenuProductIdEditRoute,
}

const AdminSettingsMenuRouteWithChildren =
  AdminSettingsMenuRoute._addFileChildren(AdminSettingsMenuRouteChildren)

interface AdminSettingsRouteChildren {
  AdminSettingsAboutRoute: typeof AdminSettingsAboutRoute
  AdminSettingsFinancialRoute: typeof AdminSettingsFinancialRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsMenuRoute: typeof AdminSettingsMenuRouteWithChildren
  AdminSettingsPlatformsRoute: typeof AdminSettingsPlatformsRoute
  AdminSettingsProductsRoute: typeof AdminSettingsProductsRoute
  AdminSettingsReceiptsRoute: typeof AdminSettingsReceiptsRoute
  AdminSettingsStaffRoute: typeof AdminSettingsStaffRoute
  AdminSettingsSystemRoute: typeof AdminSettingsSystemRoute
  AdminSettingsTablesRoute: typeof AdminSettingsTablesRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsAboutRoute: AdminSettingsAboutRoute,
  AdminSettingsFinancialRoute: AdminSettingsFinancialRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsMenuRoute: AdminSettingsMenuRouteWithChildren,
  AdminSettingsPlatformsRoute: AdminSettingsPlatformsRoute,
  AdminSettingsProductsRoute: AdminSettingsProductsRoute,
  AdminSettingsReceiptsRoute: AdminSettingsReceiptsRoute,
  AdminSettingsStaffRoute: AdminSettingsStaffRoute,
  AdminSettingsSystemRoute: AdminSettingsSystemRoute,
  AdminSettingsTablesRoute: AdminSettingsTablesRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

interface AdminRouteChildren {
  AdminBillsRoute: typeof AdminBillsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminPosRoute: typeof AdminPosRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillsRoute: AdminBillsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminPosRoute: AdminPosRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  KitchenRoute: KitchenRoute,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
