/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as TokenDisplayRouteImport } from './routes/token-display'
import { Route as StaffOnboardingRouteImport } from './routes/staff-onboarding'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LockRouteImport } from './routes/lock'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as KitchenRouteImport } from './routes/kitchen'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as CustomerDisplayRouteImport } from './routes/customer-display'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminPosRouteImport } from './routes/admin/pos'
import { Route as AdminMoreRouteImport } from './routes/admin/more'
import { Route as AdminKitchenRouteImport } from './routes/admin/kitchen'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminBillsRouteImport } from './routes/admin/bills'
import { Route as AdminMoreIndexRouteImport } from './routes/admin/more/index'
import { Route as AdminMoreVatExportRouteImport } from './routes/admin/more/vat-export'
import { Route as AdminMoreTipsRouteImport } from './routes/admin/more/tips'
import { Route as AdminMoreTablesRouteImport } from './routes/admin/more/tables'
import { Route as AdminMoreSystemRouteImport } from './routes/admin/more/system'
import { Route as AdminMoreStaffRouteImport } from './routes/admin/more/staff'
import { Route as AdminMoreReportsRouteImport } from './routes/admin/more/reports'
import { Route as AdminMoreReceiptsRouteImport } from './routes/admin/more/receipts'
import { Route as AdminMoreQrCodesRouteImport } from './routes/admin/more/qr-codes'
import { Route as AdminMorePromosRouteImport } from './routes/admin/more/promos'
import { Route as AdminMoreProductsRouteImport } from './routes/admin/more/products'
import { Route as AdminMorePlatformsRouteImport } from './routes/admin/more/platforms'
import { Route as AdminMoreMenuRouteImport } from './routes/admin/more/menu'
import { Route as AdminMoreMediaRouteImport } from './routes/admin/more/media'
import { Route as AdminMoreLocationsRouteImport } from './routes/admin/more/locations'
import { Route as AdminMoreImportRouteImport } from './routes/admin/more/import'
import { Route as AdminMoreGeneralRouteImport } from './routes/admin/more/general'
import { Route as AdminMoreFinancialRouteImport } from './routes/admin/more/financial'
import { Route as AdminMoreDiscountsRouteImport } from './routes/admin/more/discounts'
import { Route as AdminMoreCartRouteImport } from './routes/admin/more/cart'
import { Route as AdminMoreAccountRouteImport } from './routes/admin/more/account'
import { Route as AdminMoreAboutRouteImport } from './routes/admin/more/about'
import { Route as AdminMoreMenuIndexRouteImport } from './routes/admin/more/menu/index'

const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const TokenDisplayRoute = TokenDisplayRouteImport.update({
  id: '/token-display',
  path: '/token-display',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffOnboardingRoute = StaffOnboardingRouteImport.update({
  id: '/staff-onboarding',
  path: '/staff-onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LockRoute = LockRouteImport.update({
  id: '/lock',
  path: '/lock',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenRoute = KitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDisplayRoute = CustomerDisplayRouteImport.update({
  id: '/customer-display',
  path: '/customer-display',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosRoute = AdminPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreRoute = AdminMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKitchenRoute = AdminKitchenRouteImport.update({
  id: '/kitchen',
  path: '/kitchen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillsRoute = AdminBillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMoreIndexRoute = AdminMoreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreVatExportRoute = AdminMoreVatExportRouteImport.update({
  id: '/vat-export',
  path: '/vat-export',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreTipsRoute = AdminMoreTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreTablesRoute = AdminMoreTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreSystemRoute = AdminMoreSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreStaffRoute = AdminMoreStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreReportsRoute = AdminMoreReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreReceiptsRoute = AdminMoreReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreQrCodesRoute = AdminMoreQrCodesRouteImport.update({
  id: '/qr-codes',
  path: '/qr-codes',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMorePromosRoute = AdminMorePromosRouteImport.update({
  id: '/promos',
  path: '/promos',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreProductsRoute = AdminMoreProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMorePlatformsRoute = AdminMorePlatformsRouteImport.update({
  id: '/platforms',
  path: '/platforms',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreMenuRoute = AdminMoreMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreMediaRoute = AdminMoreMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreLocationsRoute = AdminMoreLocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreImportRoute = AdminMoreImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreGeneralRoute = AdminMoreGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreFinancialRoute = AdminMoreFinancialRouteImport.update({
  id: '/financial',
  path: '/financial',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreDiscountsRoute = AdminMoreDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreCartRoute = AdminMoreCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreAccountRoute = AdminMoreAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreAboutRoute = AdminMoreAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminMoreRoute,
} as any)
const AdminMoreMenuIndexRoute = AdminMoreMenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminMoreMenuRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer-display': typeof CustomerDisplayRoute
  '/kiosk': typeof KioskRoute
  '/kitchen': typeof KitchenRoute
  '/landing': typeof LandingRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/sign-up': typeof SignUpRoute
  '/staff-onboarding': typeof StaffOnboardingRoute
  '/token-display': typeof TokenDisplayRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/more': typeof AdminMoreRouteWithChildren
  '/admin/pos': typeof AdminPosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/more/about': typeof AdminMoreAboutRoute
  '/admin/more/account': typeof AdminMoreAccountRoute
  '/admin/more/cart': typeof AdminMoreCartRoute
  '/admin/more/discounts': typeof AdminMoreDiscountsRoute
  '/admin/more/financial': typeof AdminMoreFinancialRoute
  '/admin/more/general': typeof AdminMoreGeneralRoute
  '/admin/more/import': typeof AdminMoreImportRoute
  '/admin/more/locations': typeof AdminMoreLocationsRoute
  '/admin/more/media': typeof AdminMoreMediaRoute
  '/admin/more/menu': typeof AdminMoreMenuRouteWithChildren
  '/admin/more/platforms': typeof AdminMorePlatformsRoute
  '/admin/more/products': typeof AdminMoreProductsRoute
  '/admin/more/promos': typeof AdminMorePromosRoute
  '/admin/more/qr-codes': typeof AdminMoreQrCodesRoute
  '/admin/more/receipts': typeof AdminMoreReceiptsRoute
  '/admin/more/reports': typeof AdminMoreReportsRoute
  '/admin/more/staff': typeof AdminMoreStaffRoute
  '/admin/more/system': typeof AdminMoreSystemRoute
  '/admin/more/tables': typeof AdminMoreTablesRoute
  '/admin/more/tips': typeof AdminMoreTipsRoute
  '/admin/more/vat-export': typeof AdminMoreVatExportRoute
  '/admin/more/': typeof AdminMoreIndexRoute
  '/admin/more/menu/': typeof AdminMoreMenuIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-display': typeof CustomerDisplayRoute
  '/kiosk': typeof KioskRoute
  '/kitchen': typeof KitchenRoute
  '/landing': typeof LandingRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/sign-up': typeof SignUpRoute
  '/staff-onboarding': typeof StaffOnboardingRoute
  '/token-display': typeof TokenDisplayRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/pos': typeof AdminPosRoute
  '/admin': typeof AdminIndexRoute
  '/admin/more/about': typeof AdminMoreAboutRoute
  '/admin/more/account': typeof AdminMoreAccountRoute
  '/admin/more/cart': typeof AdminMoreCartRoute
  '/admin/more/discounts': typeof AdminMoreDiscountsRoute
  '/admin/more/financial': typeof AdminMoreFinancialRoute
  '/admin/more/general': typeof AdminMoreGeneralRoute
  '/admin/more/import': typeof AdminMoreImportRoute
  '/admin/more/locations': typeof AdminMoreLocationsRoute
  '/admin/more/media': typeof AdminMoreMediaRoute
  '/admin/more/platforms': typeof AdminMorePlatformsRoute
  '/admin/more/products': typeof AdminMoreProductsRoute
  '/admin/more/promos': typeof AdminMorePromosRoute
  '/admin/more/qr-codes': typeof AdminMoreQrCodesRoute
  '/admin/more/receipts': typeof AdminMoreReceiptsRoute
  '/admin/more/reports': typeof AdminMoreReportsRoute
  '/admin/more/staff': typeof AdminMoreStaffRoute
  '/admin/more/system': typeof AdminMoreSystemRoute
  '/admin/more/tables': typeof AdminMoreTablesRoute
  '/admin/more/tips': typeof AdminMoreTipsRoute
  '/admin/more/vat-export': typeof AdminMoreVatExportRoute
  '/admin/more': typeof AdminMoreIndexRoute
  '/admin/more/menu': typeof AdminMoreMenuIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/customer-display': typeof CustomerDisplayRoute
  '/kiosk': typeof KioskRoute
  '/kitchen': typeof KitchenRoute
  '/landing': typeof LandingRoute
  '/lock': typeof LockRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/setup': typeof SetupRoute
  '/sign-up': typeof SignUpRoute
  '/staff-onboarding': typeof StaffOnboardingRoute
  '/token-display': typeof TokenDisplayRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/bills': typeof AdminBillsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/kitchen': typeof AdminKitchenRoute
  '/admin/more': typeof AdminMoreRouteWithChildren
  '/admin/pos': typeof AdminPosRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/more/about': typeof AdminMoreAboutRoute
  '/admin/more/account': typeof AdminMoreAccountRoute
  '/admin/more/cart': typeof AdminMoreCartRoute
  '/admin/more/discounts': typeof AdminMoreDiscountsRoute
  '/admin/more/financial': typeof AdminMoreFinancialRoute
  '/admin/more/general': typeof AdminMoreGeneralRoute
  '/admin/more/import': typeof AdminMoreImportRoute
  '/admin/more/locations': typeof AdminMoreLocationsRoute
  '/admin/more/media': typeof AdminMoreMediaRoute
  '/admin/more/menu': typeof AdminMoreMenuRouteWithChildren
  '/admin/more/platforms': typeof AdminMorePlatformsRoute
  '/admin/more/products': typeof AdminMoreProductsRoute
  '/admin/more/promos': typeof AdminMorePromosRoute
  '/admin/more/qr-codes': typeof AdminMoreQrCodesRoute
  '/admin/more/receipts': typeof AdminMoreReceiptsRoute
  '/admin/more/reports': typeof AdminMoreReportsRoute
  '/admin/more/staff': typeof AdminMoreStaffRoute
  '/admin/more/system': typeof AdminMoreSystemRoute
  '/admin/more/tables': typeof AdminMoreTablesRoute
  '/admin/more/tips': typeof AdminMoreTipsRoute
  '/admin/more/vat-export': typeof AdminMoreVatExportRoute
  '/admin/more/': typeof AdminMoreIndexRoute
  '/admin/more/menu/': typeof AdminMoreMenuIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customer-display'
    | '/kiosk'
    | '/kitchen'
    | '/landing'
    | '/lock'
    | '/login'
    | '/register'
    | '/setup'
    | '/sign-up'
    | '/staff-onboarding'
    | '/token-display'
    | '/upgrade'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/more'
    | '/admin/pos'
    | '/admin/'
    | '/admin/more/about'
    | '/admin/more/account'
    | '/admin/more/cart'
    | '/admin/more/discounts'
    | '/admin/more/financial'
    | '/admin/more/general'
    | '/admin/more/import'
    | '/admin/more/locations'
    | '/admin/more/media'
    | '/admin/more/menu'
    | '/admin/more/platforms'
    | '/admin/more/products'
    | '/admin/more/promos'
    | '/admin/more/qr-codes'
    | '/admin/more/receipts'
    | '/admin/more/reports'
    | '/admin/more/staff'
    | '/admin/more/system'
    | '/admin/more/tables'
    | '/admin/more/tips'
    | '/admin/more/vat-export'
    | '/admin/more/'
    | '/admin/more/menu/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-display'
    | '/kiosk'
    | '/kitchen'
    | '/landing'
    | '/lock'
    | '/login'
    | '/register'
    | '/setup'
    | '/sign-up'
    | '/staff-onboarding'
    | '/token-display'
    | '/upgrade'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/pos'
    | '/admin'
    | '/admin/more/about'
    | '/admin/more/account'
    | '/admin/more/cart'
    | '/admin/more/discounts'
    | '/admin/more/financial'
    | '/admin/more/general'
    | '/admin/more/import'
    | '/admin/more/locations'
    | '/admin/more/media'
    | '/admin/more/platforms'
    | '/admin/more/products'
    | '/admin/more/promos'
    | '/admin/more/qr-codes'
    | '/admin/more/receipts'
    | '/admin/more/reports'
    | '/admin/more/staff'
    | '/admin/more/system'
    | '/admin/more/tables'
    | '/admin/more/tips'
    | '/admin/more/vat-export'
    | '/admin/more'
    | '/admin/more/menu'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customer-display'
    | '/kiosk'
    | '/kitchen'
    | '/landing'
    | '/lock'
    | '/login'
    | '/register'
    | '/setup'
    | '/sign-up'
    | '/staff-onboarding'
    | '/token-display'
    | '/upgrade'
    | '/admin/bills'
    | '/admin/customers'
    | '/admin/kitchen'
    | '/admin/more'
    | '/admin/pos'
    | '/admin/'
    | '/admin/more/about'
    | '/admin/more/account'
    | '/admin/more/cart'
    | '/admin/more/discounts'
    | '/admin/more/financial'
    | '/admin/more/general'
    | '/admin/more/import'
    | '/admin/more/locations'
    | '/admin/more/media'
    | '/admin/more/menu'
    | '/admin/more/platforms'
    | '/admin/more/products'
    | '/admin/more/promos'
    | '/admin/more/qr-codes'
    | '/admin/more/receipts'
    | '/admin/more/reports'
    | '/admin/more/staff'
    | '/admin/more/system'
    | '/admin/more/tables'
    | '/admin/more/tips'
    | '/admin/more/vat-export'
    | '/admin/more/'
    | '/admin/more/menu/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CustomerDisplayRoute: typeof CustomerDisplayRoute
  KioskRoute: typeof KioskRoute
  KitchenRoute: typeof KitchenRoute
  LandingRoute: typeof LandingRoute
  LockRoute: typeof LockRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SetupRoute: typeof SetupRoute
  SignUpRoute: typeof SignUpRoute
  StaffOnboardingRoute: typeof StaffOnboardingRoute
  TokenDisplayRoute: typeof TokenDisplayRoute
  UpgradeRoute: typeof UpgradeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/token-display': {
      id: '/token-display'
      path: '/token-display'
      fullPath: '/token-display'
      preLoaderRoute: typeof TokenDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-onboarding': {
      id: '/staff-onboarding'
      path: '/staff-onboarding'
      fullPath: '/staff-onboarding'
      preLoaderRoute: typeof StaffOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lock': {
      id: '/lock'
      path: '/lock'
      fullPath: '/lock'
      preLoaderRoute: typeof LockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen': {
      id: '/kitchen'
      path: '/kitchen'
      fullPath: '/kitchen'
      preLoaderRoute: typeof KitchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-display': {
      id: '/customer-display'
      path: '/customer-display'
      fullPath: '/customer-display'
      preLoaderRoute: typeof CustomerDisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos': {
      id: '/admin/pos'
      path: '/pos'
      fullPath: '/admin/pos'
      preLoaderRoute: typeof AdminPosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more': {
      id: '/admin/more'
      path: '/more'
      fullPath: '/admin/more'
      preLoaderRoute: typeof AdminMoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kitchen': {
      id: '/admin/kitchen'
      path: '/kitchen'
      fullPath: '/admin/kitchen'
      preLoaderRoute: typeof AdminKitchenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bills': {
      id: '/admin/bills'
      path: '/bills'
      fullPath: '/admin/bills'
      preLoaderRoute: typeof AdminBillsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/more/': {
      id: '/admin/more/'
      path: '/'
      fullPath: '/admin/more/'
      preLoaderRoute: typeof AdminMoreIndexRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/vat-export': {
      id: '/admin/more/vat-export'
      path: '/vat-export'
      fullPath: '/admin/more/vat-export'
      preLoaderRoute: typeof AdminMoreVatExportRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/tips': {
      id: '/admin/more/tips'
      path: '/tips'
      fullPath: '/admin/more/tips'
      preLoaderRoute: typeof AdminMoreTipsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/tables': {
      id: '/admin/more/tables'
      path: '/tables'
      fullPath: '/admin/more/tables'
      preLoaderRoute: typeof AdminMoreTablesRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/system': {
      id: '/admin/more/system'
      path: '/system'
      fullPath: '/admin/more/system'
      preLoaderRoute: typeof AdminMoreSystemRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/staff': {
      id: '/admin/more/staff'
      path: '/staff'
      fullPath: '/admin/more/staff'
      preLoaderRoute: typeof AdminMoreStaffRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/reports': {
      id: '/admin/more/reports'
      path: '/reports'
      fullPath: '/admin/more/reports'
      preLoaderRoute: typeof AdminMoreReportsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/receipts': {
      id: '/admin/more/receipts'
      path: '/receipts'
      fullPath: '/admin/more/receipts'
      preLoaderRoute: typeof AdminMoreReceiptsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/qr-codes': {
      id: '/admin/more/qr-codes'
      path: '/qr-codes'
      fullPath: '/admin/more/qr-codes'
      preLoaderRoute: typeof AdminMoreQrCodesRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/promos': {
      id: '/admin/more/promos'
      path: '/promos'
      fullPath: '/admin/more/promos'
      preLoaderRoute: typeof AdminMorePromosRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/products': {
      id: '/admin/more/products'
      path: '/products'
      fullPath: '/admin/more/products'
      preLoaderRoute: typeof AdminMoreProductsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/platforms': {
      id: '/admin/more/platforms'
      path: '/platforms'
      fullPath: '/admin/more/platforms'
      preLoaderRoute: typeof AdminMorePlatformsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/menu': {
      id: '/admin/more/menu'
      path: '/menu'
      fullPath: '/admin/more/menu'
      preLoaderRoute: typeof AdminMoreMenuRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/media': {
      id: '/admin/more/media'
      path: '/media'
      fullPath: '/admin/more/media'
      preLoaderRoute: typeof AdminMoreMediaRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/locations': {
      id: '/admin/more/locations'
      path: '/locations'
      fullPath: '/admin/more/locations'
      preLoaderRoute: typeof AdminMoreLocationsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/import': {
      id: '/admin/more/import'
      path: '/import'
      fullPath: '/admin/more/import'
      preLoaderRoute: typeof AdminMoreImportRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/general': {
      id: '/admin/more/general'
      path: '/general'
      fullPath: '/admin/more/general'
      preLoaderRoute: typeof AdminMoreGeneralRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/financial': {
      id: '/admin/more/financial'
      path: '/financial'
      fullPath: '/admin/more/financial'
      preLoaderRoute: typeof AdminMoreFinancialRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/discounts': {
      id: '/admin/more/discounts'
      path: '/discounts'
      fullPath: '/admin/more/discounts'
      preLoaderRoute: typeof AdminMoreDiscountsRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/cart': {
      id: '/admin/more/cart'
      path: '/cart'
      fullPath: '/admin/more/cart'
      preLoaderRoute: typeof AdminMoreCartRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/account': {
      id: '/admin/more/account'
      path: '/account'
      fullPath: '/admin/more/account'
      preLoaderRoute: typeof AdminMoreAccountRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/about': {
      id: '/admin/more/about'
      path: '/about'
      fullPath: '/admin/more/about'
      preLoaderRoute: typeof AdminMoreAboutRouteImport
      parentRoute: typeof AdminMoreRoute
    }
    '/admin/more/menu/': {
      id: '/admin/more/menu/'
      path: '/'
      fullPath: '/admin/more/menu/'
      preLoaderRoute: typeof AdminMoreMenuIndexRouteImport
      parentRoute: typeof AdminMoreMenuRoute
    }
  }
}

interface AdminMoreMenuRouteChildren {
  AdminMoreMenuIndexRoute: typeof AdminMoreMenuIndexRoute
}

const AdminMoreMenuRouteChildren: AdminMoreMenuRouteChildren = {
  AdminMoreMenuIndexRoute: AdminMoreMenuIndexRoute,
}

const AdminMoreMenuRouteWithChildren = AdminMoreMenuRoute._addFileChildren(
  AdminMoreMenuRouteChildren,
)

interface AdminMoreRouteChildren {
  AdminMoreAboutRoute: typeof AdminMoreAboutRoute
  AdminMoreAccountRoute: typeof AdminMoreAccountRoute
  AdminMoreCartRoute: typeof AdminMoreCartRoute
  AdminMoreDiscountsRoute: typeof AdminMoreDiscountsRoute
  AdminMoreFinancialRoute: typeof AdminMoreFinancialRoute
  AdminMoreGeneralRoute: typeof AdminMoreGeneralRoute
  AdminMoreImportRoute: typeof AdminMoreImportRoute
  AdminMoreLocationsRoute: typeof AdminMoreLocationsRoute
  AdminMoreMediaRoute: typeof AdminMoreMediaRoute
  AdminMoreMenuRoute: typeof AdminMoreMenuRouteWithChildren
  AdminMorePlatformsRoute: typeof AdminMorePlatformsRoute
  AdminMoreProductsRoute: typeof AdminMoreProductsRoute
  AdminMorePromosRoute: typeof AdminMorePromosRoute
  AdminMoreQrCodesRoute: typeof AdminMoreQrCodesRoute
  AdminMoreReceiptsRoute: typeof AdminMoreReceiptsRoute
  AdminMoreReportsRoute: typeof AdminMoreReportsRoute
  AdminMoreStaffRoute: typeof AdminMoreStaffRoute
  AdminMoreSystemRoute: typeof AdminMoreSystemRoute
  AdminMoreTablesRoute: typeof AdminMoreTablesRoute
  AdminMoreTipsRoute: typeof AdminMoreTipsRoute
  AdminMoreVatExportRoute: typeof AdminMoreVatExportRoute
  AdminMoreIndexRoute: typeof AdminMoreIndexRoute
}

const AdminMoreRouteChildren: AdminMoreRouteChildren = {
  AdminMoreAboutRoute: AdminMoreAboutRoute,
  AdminMoreAccountRoute: AdminMoreAccountRoute,
  AdminMoreCartRoute: AdminMoreCartRoute,
  AdminMoreDiscountsRoute: AdminMoreDiscountsRoute,
  AdminMoreFinancialRoute: AdminMoreFinancialRoute,
  AdminMoreGeneralRoute: AdminMoreGeneralRoute,
  AdminMoreImportRoute: AdminMoreImportRoute,
  AdminMoreLocationsRoute: AdminMoreLocationsRoute,
  AdminMoreMediaRoute: AdminMoreMediaRoute,
  AdminMoreMenuRoute: AdminMoreMenuRouteWithChildren,
  AdminMorePlatformsRoute: AdminMorePlatformsRoute,
  AdminMoreProductsRoute: AdminMoreProductsRoute,
  AdminMorePromosRoute: AdminMorePromosRoute,
  AdminMoreQrCodesRoute: AdminMoreQrCodesRoute,
  AdminMoreReceiptsRoute: AdminMoreReceiptsRoute,
  AdminMoreReportsRoute: AdminMoreReportsRoute,
  AdminMoreStaffRoute: AdminMoreStaffRoute,
  AdminMoreSystemRoute: AdminMoreSystemRoute,
  AdminMoreTablesRoute: AdminMoreTablesRoute,
  AdminMoreTipsRoute: AdminMoreTipsRoute,
  AdminMoreVatExportRoute: AdminMoreVatExportRoute,
  AdminMoreIndexRoute: AdminMoreIndexRoute,
}

const AdminMoreRouteWithChildren = AdminMoreRoute._addFileChildren(
  AdminMoreRouteChildren,
)

interface AdminRouteChildren {
  AdminBillsRoute: typeof AdminBillsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminKitchenRoute: typeof AdminKitchenRoute
  AdminMoreRoute: typeof AdminMoreRouteWithChildren
  AdminPosRoute: typeof AdminPosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillsRoute: AdminBillsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminKitchenRoute: AdminKitchenRoute,
  AdminMoreRoute: AdminMoreRouteWithChildren,
  AdminPosRoute: AdminPosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CustomerDisplayRoute: CustomerDisplayRoute,
  KioskRoute: KioskRoute,
  KitchenRoute: KitchenRoute,
  LandingRoute: LandingRoute,
  LockRoute: LockRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SetupRoute: SetupRoute,
  SignUpRoute: SignUpRoute,
  StaffOnboardingRoute: StaffOnboardingRoute,
  TokenDisplayRoute: TokenDisplayRoute,
  UpgradeRoute: UpgradeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
